# Generated by Django 3.1.8 on 2021-12-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='name',
        ),
    ]
